-------------------------------CREATE TABLE-------------------------------
CREATE TABLE SVZ98608.Approval(
   pkApproval BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   observation VARCHAR(16320) NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkUser BIGINT NOT NULL,
   fkScreenApproval BIGINT NOT NULL,
   PRIMARY KEY(pkApproval)
);

CREATE TABLE SVZ98608.HelpCenterMessages(
   pkHelpCenterMessages BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   message VARCHAR(16320) NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL,
   fkUser BIGINT NOT NULL,
   fkUserCompany BIGINT,
   fkHelpCenterAssistant BIGINT,
   PRIMARY KEY(pkHelpCenterMessages)
);

CREATE TABLE SVZ98608.HelpCenter(
   pkHelpCenter BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   number INT NOT NULL DEFAULT 1,
   protocol VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   message VARCHAR(16320) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkContactPhone BIGINT,
   fkContactEmail BIGINT,
   fkHelpCenterServicesTypes BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkHelpCenter)
);

CREATE TABLE SVZ98608.HelpCenterTypicalAsks(
   pkHelpCenterTypicalAsks BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   number INT,
   ask VARCHAR(255) NOT NULL,
   answer VARCHAR(16320) NOT NULL,
   fkHelpCenterTypicalAsks BIGINT,
   fkLanguage SMALLINT NOT NULL,
   PRIMARY KEY(pkHelpCenterTypicalAsks)
);

CREATE TABLE SVZ98608.HelpCenterService(
   pkHelpCenterService BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   date VARCHAR(26) NOT NULL,
   message VARCHAR(16320) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkHelpCenter BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   fkEmail BIGINT,
   fkSMS BIGINT,
   PRIMARY KEY(pkHelpCenterService)
);

CREATE TABLE SVZ98608.Email(
   pkEmail BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   subject VARCHAR(255) NOT NULL,
   emailText VARCHAR(16320) NOT NULL,
   fkEmailController BIGINT,
   fkContact BIGINT,
   PRIMARY KEY(pkEmail)
);

CREATE TABLE SVZ98608.Log(
   pkLog BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   type INT NOT NULL,
   title VARCHAR(255) NOT NULL,
   message VARCHAR(16320) NOT NULL,
   date VARCHAR(26) NOT NULL,
   fkCountry SMALLINT NOT NULL,
   PRIMARY KEY(pkLog)
);

CREATE TABLE SVZ98608.LoanBankProgram(
   pkLoanBankProgram BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(255) NOT NULL,
   description VARCHAR(16320) NOT NULL,
   beginning VARCHAR(26) NOT NULL,
   end VARCHAR(26) NOT NULL,
   interestRate REAL NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkBank BIGINT NOT NULL,
   fkLoanBankProgramProfile BIGINT,
   fkScreenApproval BIGINT,
   PRIMARY KEY(pkLoanBankProgram)
);

CREATE TABLE SVZ98608.ServiceOrderCanceled(
   pkServiceOrderCanceled BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   date VARCHAR(26),
   detail VARCHAR(16320) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   pkServiceOrder BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkServiceOrderCanceled)
);

CREATE TABLE SVZ98608.FiscalModuleFunction(
   pkFiscalModuleFunction BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   url VARCHAR(16320) NOT NULL,
   template VARCHAR(16320) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkFiscalModule BIGINT NOT NULL,
   PRIMARY KEY(pkFiscalModuleFunction)
);

CREATE TABLE SVZ98608.FiscalModule(
   pkFiscalModule BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   code VARCHAR(255) NOT NULL,
   url VARCHAR(16320) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkTaxSettings BIGINT NOT NULL,
   PRIMARY KEY(pkFiscalModule)
);

CREATE TABLE SVZ98608.FinancialModuleFunction(
   pkFinancialModuleFunction BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   type INT NOT NULL,
   name VARCHAR(255) NOT NULL,
   information VARCHAR(16320),
   status INT NOT NULL DEFAULT 0,
   fkFinancialModule INT NOT NULL,
   PRIMARY KEY(pkFinancialModuleFunction)
);

-------------------------------CREATE TABLE-------------------------------

-------------------------------FOREIGN KEY--------------------------------
ALTER TABLE SVZ98608.Approval
   FOREIGN KEY (fkUser)
       REFERENCES User (pkUser)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.Approval
   FOREIGN KEY (fkScreenApproval)
       REFERENCES ScreenApproval (pkScreenApproval)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterMessages
   FOREIGN KEY (fkUser)
       REFERENCES User (pkUser)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterMessages
   FOREIGN KEY (fkUserCompany)
       REFERENCES User (pkUser)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterMessages
   FOREIGN KEY (fkHelpCenterAssistant)
       REFERENCES HelpCenterAssistant (pkHelpCenterAssistant)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenter
   FOREIGN KEY (fkContactPhone)
       REFERENCES Contact (pkContact)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenter
   FOREIGN KEY (fkContactEmail)
       REFERENCES Contact (pkContact)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenter
   FOREIGN KEY (fkHelpCenterServicesTypes)
       REFERENCES HelpCenterServicesTypes (pkHelpCenterServicesTypes)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenter
   FOREIGN KEY (fkUser)
       REFERENCES User (pkUser)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterTypicalAsks
   FOREIGN KEY (fkHelpCenterTypicalAsks)
       REFERENCES HelpCenterTypicalAsks (pkHelpCenterTypicalAsks)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterTypicalAsks
   FOREIGN KEY (fkLanguage)
       REFERENCES Language (pkLanguage)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterService
   FOREIGN KEY (fkHelpCenter)
       REFERENCES HelpCenter (pkHelpCenter)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterService
   FOREIGN KEY (fkUser)
       REFERENCES User (pkUser)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterService
   FOREIGN KEY (fkEmail)
       REFERENCES Email (pkEmail)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.HelpCenterService
   FOREIGN KEY (fkSMS)
       REFERENCES SMS (pkSMS)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.Email
   FOREIGN KEY (fkEmailController)
       REFERENCES EmailController (pkEmailController)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.Email
   FOREIGN KEY (fkContact)
       REFERENCES Contact (pkContact)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.Log
   FOREIGN KEY (fkCountry)
       REFERENCES Country (pkCountry)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.LoanBankProgram
   FOREIGN KEY (fkBank)
       REFERENCES Bank (pkBank)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.LoanBankProgram
   FOREIGN KEY (fkLoanBankProgramProfile)
       REFERENCES LoanBankProgramProfile (pkLoanBankProgramProfile)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.LoanBankProgram
   FOREIGN KEY (fkScreenApproval)
       REFERENCES ScreenApproval (pkScreenApproval)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.ServiceOrderCanceled
   FOREIGN KEY (pkServiceOrder)
       REFERENCES ServiceOrder (pkServiceOrder)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.ServiceOrderCanceled
   FOREIGN KEY (fkUser)
       REFERENCES User (pkUser)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.FiscalModuleFunction
   FOREIGN KEY (fkFiscalModule)
       REFERENCES FiscalModule (pkFiscalModule)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.FiscalModule
   FOREIGN KEY (fkTaxSettings)
       REFERENCES TaxSettings (pkTaxSettings)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

ALTER TABLE SVZ98608.FinancialModuleFunction
   FOREIGN KEY (fkFinancialModule)
       REFERENCES FinancialModule (pkFinancialModule)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

-------------------------------FOREIGN KEY--------------------------------

--------------------------------ADD COLUMN--------------------------------
ALTER TABLE SVZ98608.Person ADD COLUMN 
   passedAway DATE;

ALTER TABLE SVZ98608.Person ADD COLUMN 
   statusPerson INT NOT NULL DEFAULT 0;

--------------------------------ADD COLUMN--------------------------------

-------------------------------DROP COLUMN--------------------------------
ALTER TABLE SVZ98608.Person DROP COLUMN NEWPRIMARY;
ALTER TABLE SVZ98608.Person DROP COLUMN STATUS;
-------------------------------DROP COLUMN--------------------------------

-------------------------------DROP TABLE---------------------------------
DROP TABLE SVZ98608.NEWTABLE;
-------------------------------DROP TABLE---------------------------------

