CREATE TABLE SVZ98608.Person(
   pkPerson BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   lastName VARCHAR(255) NOT NULL,
   bithday DATE NOT NULL,
   maritalStatus INT NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkBirthCountry SMALLINT NOT NULL,
   PRIMARY KEY(pkPerson)
   FOREIGN KEY (fkBirthCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.JuridicalPerson(
   pkJuridicalPerson BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   socialReason VARCHAR(255) NOT NULL,
   openedDate DATE NOT NULL,
   companyType INT NOT NULL DEFAULT 1,
   legalStructure INT NOT NULL DEFAULT 1,
   fkOriginCountry SMALLINT,
   PRIMARY KEY(pkJuridicalPerson)
   FOREIGN KEY (fkOriginCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.IdentificationDocument(
   pkIdentificationDocument BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type VARCHAR(255) NOT NULL,
   value VARCHAR(255) NOT NULL,
   issueDate DATE,
   expirationDate DATE,
   status INT NOT NULL DEFAULT 0,
   fkPerson BIGINT,
   fkJuridicalPerson BIGINT,
   fkState SMALLINT,
   fkCountry SMALLINT,
   PRIMARY KEY(pkIdentificationDocument)
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkState)
      REFERENCES State (pkState)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.User(
   pkUser BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   dateOfCreatingAccount VARCHAR(26) NOT NULL,
   dateOfFinishingAccount VARCHAR(26),
   facebookAccount VARCHAR(255),
   useTwoStepsVerification BOOLEAN NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPerson BIGINT,
   fkJuridicalPerson BIGINT,
   fkEmployee BIGINT,
   fkCounter BIGINT,
   fkBalance BIGINT NOT NULL,
   PRIMARY KEY(pkUser)
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkEmployee)
      REFERENCES Employee (pkEmployee)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCounter)
      REFERENCES Counter (pkCounter)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalance)
      REFERENCES Balance (pkBalance)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Contact(
   pkContact BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type VARCHAR(255) NOT NULL,
   value VARCHAR(255) NOT NULL,
   expirationDate DATE,
   status INT NOT NULL DEFAULT 0,
   fkPerson BIGINT,
   fkJuridicalPerson BIGINT,
   PRIMARY KEY(pkContact)
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Address(
   pkAddress BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL DEFAULT 1,
   street VARCHAR(255) NOT NULL,
   number VARCHAR(255) NOT NULL,
   neighborhood VARCHAR(255) NOT NULL,
   zipCode VARCHAR(255),
   status INT NOT NULL DEFAULT 0,
   fkPerson BIGINT,
   fkJuridicalPerson BIGINT,
   fkCity BIGINT NOT NULL,
   PRIMARY KEY(pkAddress)
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCity)
      REFERENCES City (pkCity)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.State(
   pkState SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   abbreviation VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCountry SMALLINT NOT NULL,
   PRIMARY KEY(pkState)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Country(
   pkCountry SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   abbreviation VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   timeZone INT,
   fkLanguage SMALLINT NOT NULL,
   PRIMARY KEY(pkCountry)
   FOREIGN KEY (fkLanguage)
      REFERENCES Language (pkLanguage)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.City(
   pkCity BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   abbreviation VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkState SMALLINT NOT NULL,
   fkDepartmentOfFinance SMALLINT,
   fkBalance BIGINT,
   PRIMARY KEY(pkCity)
   FOREIGN KEY (fkState)
      REFERENCES State (pkState)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkDepartmentOfFinance)
      REFERENCES DepartmentOfFinance (pkDepartmentOfFinance)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalance)
      REFERENCES Balance (pkBalance)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Employee(
   pkEmployee BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   profession VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPerson BIGINT NOT NULL,
   fkJuridicalPerson BIGINT NOT NULL,
   PRIMARY KEY(pkEmployee)
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.EmployeeResponsibility(
   pkEmployeeResponsibility BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   position VARCHAR(255) NOT NULL,
   salary REAL NOT NULL,
   commission REAL NOT NULL,
   beginning VARCHAR(26) NOT NULL,
   end VARCHAR(26),
   status INT NOT NULL DEFAULT 0,
   fkEmployee BIGINT NOT NULL,
   PRIMARY KEY(pkEmployeeResponsibility)
   FOREIGN KEY (fkEmployee)
      REFERENCES Employee (pkEmployee)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Appointment(
   pkAppointment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   number VARCHAR(255) NOT NULL,
   cost REAL NOT NULL,
   discount REAL NOT NULL DEFAULT 0,
   date DATE NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkAppointment)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Service(
   pkService BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   cost REAL NOT NULL,
   time INT NOT NULL,
   discountRate REAL NOT NULL DEFAULT 0,
   cancelRate REAL NOT NULL DEFAULT 0,
   withContract BOOLEAN NOT NULL DEFAULT false,
   status INT NOT NULL DEFAULT 0,
   fkEmployeeResponsibility BIGINT,
   fkAddress BIGINT,
   fkServiceCategory BIGINT NOT NULL,
   fkJuridicalPerson BIGINT,
   PRIMARY KEY(pkService)
   FOREIGN KEY (fkEmployeeResponsibility)
      REFERENCES EmployeeResponsibility (pkEmployeeResponsibility)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAddress)
      REFERENCES Address (pkAddress)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkServiceCategory)
      REFERENCES ServiceCategory (pkServiceCategory)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceAppointment(
   pkServiceAppointment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   beginning VARCHAR(26),
   end VARCHAR(26),
   status INT NOT NULL DEFAULT 0,
   fkService BIGINT NOT NULL,
   fkAppointment BIGINT NOT NULL,
   PRIMARY KEY(pkServiceAppointment)
   FOREIGN KEY (fkService)
      REFERENCES Service (pkService)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAppointment)
      REFERENCES Appointment (pkAppointment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceCategory(
   pkServiceCategory BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCategory BIGINT,
   PRIMARY KEY(pkServiceCategory)
   FOREIGN KEY (fkCategory)
      REFERENCES Category (pkCategory)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Category(
   pkCategory BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255),
   status INT NOT NULL DEFAULT 0,
   fkCategory BIGINT,
   fkCountry SMALLINT,
   PRIMARY KEY(pkCategory)
   FOREIGN KEY (fkCategory)
      REFERENCES Category (pkCategory)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceUnavailable(
   pkServiceUnavailable BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   beginning DATE NOT NULL,
   end DATE,
   status INT NOT NULL DEFAULT 0,
   fkService BIGINT NOT NULL,
   PRIMARY KEY(pkServiceUnavailable)
   FOREIGN KEY (fkService)
      REFERENCES Service (pkService)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceOrder(
   pkServiceOrder BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   code VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   cost REAL NOT NULL,
   discount REAL NOT NULL DEFAULT 0,
   fee REAL NOT NULL DEFAULT 0,
   total REAL NOT NULL,
   primaryPayment INT NOT NULL DEFAULT 1,
   status INT NOT NULL DEFAULT 0,
   fkAppointment BIGINT NOT NULL,
   fkJuridicalPerson BIGINT NOT NULL,
   fkCurrency BIGINT NOT NULL,
   fkPerson BIGINT,
   fkAddress BIGINT,
   PRIMARY KEY(pkServiceOrder)
   FOREIGN KEY (fkAppointment)
      REFERENCES Appointment (pkAppointment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCurrency)
      REFERENCES Currency (pkCurrency)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAddress)
      REFERENCES Address (pkAddress)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserPayment(
   pkUserPayment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL,
   date VARCHAR(26) NOT NULL,
   default BOOLEAN NOT NULL DEFAULT false,
   status INT NOT NULL DEFAULT 0,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkUserPayment)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceOrderPayment(
   pkServiceOrderPayment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   number INT NOT NULL,
   note VARCHAR(255),
   date VARCHAR(26) NOT NULL,
   value REAL NOT NULL,
   paymentType INT NOT NULL DEFAULT 1,
   status INT NOT NULL DEFAULT 0,
   fkServiceOrder BIGINT NOT NULL,
   fkPayment BIGINT,
   fkBalanceItem BIGINT,
   PRIMARY KEY(pkServiceOrderPayment)
   FOREIGN KEY (fkServiceOrder)
      REFERENCES ServiceOrder (pkServiceOrder)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceItem)
      REFERENCES BalanceItem (pkBalanceItem)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxReceipt(
   pkTaxReceipt BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   code VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   dateCanceled VARCHAR(26),
   status INT NOT NULL DEFAULT 0,
   fkUser BIGINT NOT NULL,
   fkEmail BIGINT NOT NULL,
   fkServiceOrder BIGINT NOT NULL,
   fkCity BIGINT NOT NULL,
   pkServiceOrderCanceled BIGINT,
   fkTaxReceiptCounterApproved BIGINT,
   PRIMARY KEY(pkTaxReceipt)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkEmail)
      REFERENCES Email (pkEmail)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkServiceOrder)
      REFERENCES ServiceOrder (pkServiceOrder)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCity)
      REFERENCES City (pkCity)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (pkServiceOrderCanceled)
      REFERENCES ServiceOrderCanceled (pkServiceOrderCanceled)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxReceiptCounterApproved)
      REFERENCES TaxReceiptCounterApproved (pkTaxReceiptCounterApproved)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Balance(
   pkBalance BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   value REAL NOT NULL,
   consolidatedValue REAL,
   consolidatedDate VARCHAR(26),
   status INT NOT NULL DEFAULT 0,
   fkCurrency BIGINT NOT NULL,
   fkJuridicalPerson BIGINT,
   fkPerson BIGINT,
   PRIMARY KEY(pkBalance)
   FOREIGN KEY (fkCurrency)
      REFERENCES Currency (pkCurrency)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceOrderTax(
   pkServiceOrderTax BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   note VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   value REAL NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkServiceOrder BIGINT NOT NULL,
   fkTaxFormula BIGINT NOT NULL,
   fkTaxSetting BIGINT NOT NULL,
   fkTaxReceipt BIGINT,
   PRIMARY KEY(pkServiceOrderTax)
   FOREIGN KEY (fkServiceOrder)
      REFERENCES ServiceOrder (pkServiceOrder)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxFormula)
      REFERENCES TaxFormula (pkTaxFormula)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxSetting)
      REFERENCES TaxSettings (pkTaxSettings)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxReceipt)
      REFERENCES TaxReceipt (pkTaxReceipt)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxSettings(
   pkTaxSettings BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   filedDate VARCHAR(26) NOT NULL,
   approvatedDate VARCHAR(26),
   expiredDate VARCHAR(26),
   observation VARCHAR(32704) NOT NULL,
   localType INT NOT NULL DEFAULT 1,
   hasRevenue BOOLEAN NOT NULL DEFAULT false,
   transferTaxPeriod INT NOT NULL DEFAULT 1,
   transferTaxDay INT NOT NULL DEFAULT 1,
   status INT NOT NULL DEFAULT 0,
   fkCity BIGINT NOT NULL,
   fkScreenApproval BIGINT NOT NULL,
   fkCityAccount BIGINT NOT NULL,
   fkCounter BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkTaxSettings)
   FOREIGN KEY (fkCity)
      REFERENCES City (pkCity)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkScreenApproval)
      REFERENCES ScreenApproval (pkScreenApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCityAccount)
      REFERENCES CityAccount (pkCityAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCounter)
      REFERENCES Counter (pkCounter)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Attachment(
   pkAttachment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   type VARCHAR(255) NOT NULL,
   path VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   PRIMARY KEY(pkAttachment)
);

CREATE TABLE SVZ98608.TaxSettingAttachment(
   pkTaxSettingAttachment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkTaxSetting BIGINT NOT NULL,
   fkAttachment BIGINT NOT NULL,
   PRIMARY KEY(pkTaxSettingAttachment)
   FOREIGN KEY (fkTaxSetting)
      REFERENCES TaxSettings (pkTaxSettings)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserAttachment(
   pkUserAttachment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   isProfilePicture BOOLEAN NOT NULL DEFAULT false,
   status INT NOT NULL DEFAULT 0,
   fkAttachment BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   fkIdentificationDocument BIGINT,
   PRIMARY KEY(pkUserAttachment)
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkIdentificationDocument)
      REFERENCES IdentificationDocument (pkIdentificationDocument)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxSettingsCategory(
   pkTaxSettingsCategory BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   tax REAL,
   localType INT NOT NULL DEFAULT 1,
   freeTax BOOLEAN NOT NULL DEFAULT false,
   status INT NOT NULL,
   fkTaxSettings BIGINT,
   fkCategory BIGINT,
   PRIMARY KEY(pkTaxSettingsCategory)
   FOREIGN KEY (fkTaxSettings)
      REFERENCES TaxSettings (pkTaxSettings)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCategory)
      REFERENCES Category (pkCategory)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceTemplateContract(
   pkServiceTemplateContract BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   beginning VARCHAR(26) NOT NULL,
   end VARCHAR(26),
   status INT NOT NULL,
   fkCategoryContractTemplate BIGINT NOT NULL,
   fkService BIGINT NOT NULL,
   fkTemplateAttachment BIGINT NOT NULL,
   fkSignatureAttachment BIGINT NOT NULL,
   PRIMARY KEY(pkServiceTemplateContract)
   FOREIGN KEY (fkCategoryContractTemplate)
      REFERENCES CategoryContractTemplate (pkCategoryContractTemplate)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkService)
      REFERENCES Service (pkService)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTemplateAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkSignatureAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserSettings(
   pkUserSettings BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkUser BIGINT NOT NULL,
   fkSignatureAttachment BIGINT,
   PRIMARY KEY(pkUserSettings)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkSignatureAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Approval(
   pkApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   observation VARCHAR(32704) NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkUser BIGINT NOT NULL,
   fkScreenApproval BIGINT NOT NULL,
   PRIMARY KEY(pkApproval)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkScreenApproval)
      REFERENCES ScreenApproval (pkScreenApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Screen(
   pkScreen BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   id INT NOT NULL,
   name VARCHAR(255) NOT NULL,
   path VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   PRIMARY KEY(pkScreen)
);

CREATE TABLE SVZ98608.ScreenPermission(
   pkPermissionPermission BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   permission INT NOT NULL DEFAULT 1,
   status INT NOT NULL DEFAULT 0,
   fkScreen BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkPermissionPermission)
   FOREIGN KEY (fkScreen)
      REFERENCES Screen (pkScreen)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ScreenApproval(
   pkScreenApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   pathComplement VARCHAR(255),
   status INT NOT NULL DEFAULT 0,
   fkScreen BIGINT NOT NULL,
   fkCountry SMALLINT,
   PRIMARY KEY(pkScreenApproval)
   FOREIGN KEY (fkScreen)
      REFERENCES Screen (pkScreen)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.PrepayTax(
   pkPrepayTax BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   value REAL NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkUser BIGINT NOT NULL,
   fkPayment BIGINT,
   fkBalanceItem BIGINT,
   PRIMARY KEY(pkPrepayTax)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceItem)
      REFERENCES BalanceItem (pkBalanceItem)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Payment(
   pkPayment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL DEFAULT 1,
   date VARCHAR(26) NOT NULL,
   value REAL NOT NULL,
   note VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCurrency BIGINT NOT NULL,
   fkBalanceItem BIGINT NOT NULL,
   fkMainBankAccount BIGINT NOT NULL,
   PRIMARY KEY(pkPayment)
   FOREIGN KEY (fkCurrency)
      REFERENCES Currency (pkCurrency)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceItem)
      REFERENCES BalanceItem (pkBalanceItem)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkMainBankAccount)
      REFERENCES MainBankAccount (pkMainBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Bank(
   pkBank BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCountry SMALLINT,
   fkJuridicalPerson BIGINT,
   PRIMARY KEY(pkBank)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.PaymentDebt(
   pkPaymentDebt BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPayment BIGINT NOT NULL,
   fkBankAccount BIGINT NOT NULL,
   PRIMARY KEY(pkPaymentDebt)
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.PaymentBill(
   pkPaymentBill BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPayment BIGINT NOT NULL,
   fkPerson BIGINT NOT NULL,
   PRIMARY KEY(pkPaymentBill)
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.BankAccount(
   pkBankAccount BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   branch VARCHAR(255) NOT NULL,
   account VARCHAR(255) NOT NULL,
   validatedAccount DATE,
   status INT NOT NULL DEFAULT 0,
   fkCurrency BIGINT NOT NULL,
   fkJuridicalPerson BIGINT,
   fkPerson BIGINT,
   fkBank BIGINT NOT NULL,
   fkBankBranch BIGINT,
   PRIMARY KEY(pkBankAccount)
   FOREIGN KEY (fkCurrency)
      REFERENCES Currency (pkCurrency)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBank)
      REFERENCES Bank (pkBank)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankBranch)
      REFERENCES BankBranch (pkBankBranch)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.WithdrawMoney(
   pkWithdrawMoney BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   value REAL NOT NULL,
   date VARCHAR(26) NOT NULL,
   dateApprovated VARCHAR(26),
   status INT NOT NULL DEFAULT 0,
   fkTransferMoney BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   fkScreenApproval BIGINT,
   PRIMARY KEY(pkWithdrawMoney)
   FOREIGN KEY (fkTransferMoney)
      REFERENCES TransferMoney (pkTransferMoney)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkScreenApproval)
      REFERENCES ScreenApproval (pkScreenApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Currency(
   pkCurrency BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   symbol VARCHAR(255) NOT NULL,
   status INT NOT NULL,
   fkCountry SMALLINT,
   PRIMARY KEY(pkCurrency)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Language(
   pkLanguage SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCountry SMALLINT,
   PRIMARY KEY(pkLanguage)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.PaymentCredit(
   pkPaymentCredit BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   transactionId VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPayment BIGINT NOT NULL,
   fkUserPaymentCreditCard BIGINT NOT NULL,
   PRIMARY KEY(pkPaymentCredit)
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUserPaymentCreditCard)
      REFERENCES UserPaymentCreditCard (pkUserPaymentCreditCard)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.PaymentDigitalWallet(
   pkPaymentDigitalWallet BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPayment BIGINT,
   fkUserPaymentDigitalWallet BIGINT,
   PRIMARY KEY(pkPaymentDigitalWallet)
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUserPaymentDigitalWallet)
      REFERENCES UserPaymentDigitalWallet (pkUserPaymentDigitalWallet)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.DigitalWallet(
   pkDigitalWallet BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   status INT NOT NULL,
   fkCountry SMALLINT,
   PRIMARY KEY(pkDigitalWallet)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.CreditCardBrand(
   pkCreditCardBrand BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   status INT NOT NULL,
   fkCountry SMALLINT,
   PRIMARY KEY(pkCreditCardBrand)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.MainBankAccount(
   pkMainBankAccount BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkBalance BIGINT NOT NULL,
   fkBankAccount BIGINT NOT NULL,
   fkCountry SMALLINT NOT NULL,
   fkScreenApproval BIGINT NOT NULL,
   fkUserCreator BIGINT NOT NULL,
   PRIMARY KEY(pkMainBankAccount)
   FOREIGN KEY (fkBalance)
      REFERENCES Balance (pkBalance)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkScreenApproval)
      REFERENCES ScreenApproval (pkScreenApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUserCreator)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TransferMoney(
   pkTransferMoney BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL,
   note VARCHAR(255) NOT NULL,
   value REAL NOT NULL,
   date VARCHAR(26) NOT NULL,
   identification VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkFromMainBankAccount BIGINT NOT NULL,
   fkToBankAccount BIGINT NOT NULL,
   fkCurrency BIGINT NOT NULL,
   fkBalanceItem BIGINT,
   PRIMARY KEY(pkTransferMoney)
   FOREIGN KEY (fkFromMainBankAccount)
      REFERENCES MainBankAccount (pkMainBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkToBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCurrency)
      REFERENCES Currency (pkCurrency)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceItem)
      REFERENCES BalanceItem (pkBalanceItem)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.HelpCenterServicesTypes(
   pkHelpCenterServicesTypes BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   type INT NOT NULL DEFAULT 1,
   status INT NOT NULL DEFAULT 0,
   fkHelpCenterServicesTypes BIGINT,
   PRIMARY KEY(pkHelpCenterServicesTypes)
   FOREIGN KEY (fkHelpCenterServicesTypes)
      REFERENCES HelpCenterServicesTypes (pkHelpCenterServicesTypes)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.HelpCenterMessages(
   pkHelpCenterMessages BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   message VARCHAR(32704) NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL,
   fkUser BIGINT NOT NULL,
   fkUserCompany BIGINT,
   fkHelpCenterAssistant BIGINT,
   PRIMARY KEY(pkHelpCenterMessages)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUserCompany)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkHelpCenterAssistant)
      REFERENCES HelpCenterAssistant (pkHelpCenterAssistant)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.HelpCenterAssistant(
   pkHelpCenterAssistant BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkJuridicalPerson BIGINT NOT NULL,
   PRIMARY KEY(pkHelpCenterAssistant)
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.HelpCenter(
   pkHelpCenter BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   number INT NOT NULL DEFAULT 1,
   protocol VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   message VARCHAR(32704) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkContactPhone BIGINT,
   fkContactEmail BIGINT,
   fkHelpCenterServicesTypes BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkHelpCenter)
   FOREIGN KEY (fkContactPhone)
      REFERENCES Contact (pkContact)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkContactEmail)
      REFERENCES Contact (pkContact)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkHelpCenterServicesTypes)
      REFERENCES HelpCenterServicesTypes (pkHelpCenterServicesTypes)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserPaymentDigitalWallet(
   pkUserPaymentDigitalWallet BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   userCodeAccess VARCHAR(255) NOT NULL,
   datePairedUp VARCHAR(26) NOT NULL,
   fkDigitalWallet BIGINT NOT NULL,
   fkUserPayment BIGINT NOT NULL,
   PRIMARY KEY(pkUserPaymentDigitalWallet)
   FOREIGN KEY (fkDigitalWallet)
      REFERENCES DigitalWallet (pkDigitalWallet)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUserPayment)
      REFERENCES UserPayment (pkUserPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserPaymentCreditCard(
   pkUserPaymentCreditCard BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   cardNumber VARCHAR(255) NOT NULL,
   nameOnCard VARCHAR(255) NOT NULL,
   expirationDate DATE NOT NULL,
   pairingId VARCHAR(255),
   fkCreditCardBrand BIGINT NOT NULL,
   fkUserPayment BIGINT NOT NULL,
   fkBillingAddress BIGINT,
   pkShippingAddress BIGINT,
   PRIMARY KEY(pkUserPaymentCreditCard)
   FOREIGN KEY (fkCreditCardBrand)
      REFERENCES CreditCardBrand (pkCreditCardBrand)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUserPayment)
      REFERENCES UserPayment (pkUserPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBillingAddress)
      REFERENCES Address (pkAddress)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (pkShippingAddress)
      REFERENCES Address (pkAddress)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ApprovalAttachment(
   pkApprovalAttachment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkApproval BIGINT NOT NULL,
   fkAttachment BIGINT NOT NULL,
   PRIMARY KEY(pkApprovalAttachment)
   FOREIGN KEY (fkApproval)
      REFERENCES Approval (pkApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.HelpCenterTypicalAsks(
   pkHelpCenterTypicalAsks BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   number INT,
   ask VARCHAR(255) NOT NULL,
   answer VARCHAR(32704) NOT NULL,
   fkHelpCenterTypicalAsks BIGINT,
   fkLanguage SMALLINT NOT NULL,
   PRIMARY KEY(pkHelpCenterTypicalAsks)
   FOREIGN KEY (fkHelpCenterTypicalAsks)
      REFERENCES HelpCenterTypicalAsks (pkHelpCenterTypicalAsks)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLanguage)
      REFERENCES Language (pkLanguage)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.HelpCenterService(
   pkHelpCenterService BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date VARCHAR(26) NOT NULL,
   message VARCHAR(32704) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkHelpCenter BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   fkEmail BIGINT,
   fkSMS BIGINT,
   PRIMARY KEY(pkHelpCenterService)
   FOREIGN KEY (fkHelpCenter)
      REFERENCES HelpCenter (pkHelpCenter)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkEmail)
      REFERENCES Email (pkEmail)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkSMS)
      REFERENCES SMS (pkSMS)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.EmailController(
   pkEmailController BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL DEFAULT 1,
   imap VARCHAR(255) NOT NULL,
   smtp VARCHAR(255) NOT NULL,
   fullName VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCountry SMALLINT NOT NULL,
   PRIMARY KEY(pkEmailController)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.SMSController(
   pkSMSController INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL DEFAULT 1,
   number VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCountry SMALLINT NOT NULL,
   PRIMARY KEY(pkSMSController)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Email(
   pkEmail BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   subject VARCHAR(255) NOT NULL,
   emailText VARCHAR(32704) NOT NULL,
   fkEmailController BIGINT,
   fkContact BIGINT,
   PRIMARY KEY(pkEmail)
   FOREIGN KEY (fkEmailController)
      REFERENCES EmailController (pkEmailController)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkContact)
      REFERENCES Contact (pkContact)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.SMS(
   pkSMS BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   smsText VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkSMSController INT,
   PRIMARY KEY(pkSMS)
   FOREIGN KEY (fkSMSController)
      REFERENCES SMSController (pkSMSController)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserActivation(
   pkUserActivation BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL DEFAULT 1,
   code VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   dateActive VARCHAR(26),
   status INT NOT NULL,
   fkUserLogin BIGINT NOT NULL,
   fkEmail BIGINT,
   fkSMS BIGINT,
   fkUserTwoStepsVerification BIGINT,
   PRIMARY KEY(pkUserActivation)
   FOREIGN KEY (fkUserLogin)
      REFERENCES UserLogin (pkUserLogin)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkEmail)
      REFERENCES Email (pkEmail)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkSMS)
      REFERENCES SMS (pkSMS)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUserTwoStepsVerification)
      REFERENCES UserTwoStepsVerification (pkUserTwoStepsVerification)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserLogin(
   pkUserLogin BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   dispositive VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   trust BOOLEAN NOT NULL DEFAULT false,
   status INT NOT NULL DEFAULT 0,
   fkAddress BIGINT NOT NULL,
   fkUser BIGINT,
   PRIMARY KEY(pkUserLogin)
   FOREIGN KEY (fkAddress)
      REFERENCES Address (pkAddress)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserTwoStepsVerification(
   pkUserTwoStepsVerification BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   dispositive VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   datePaired VARCHAR(26) NOT NULL,
   status INT NOT NULL,
   fkUser BIGINT,
   PRIMARY KEY(pkUserTwoStepsVerification)
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Log(
   pkLog BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL,
   title VARCHAR(255) NOT NULL,
   message VARCHAR(32704) NOT NULL,
   date VARCHAR(26) NOT NULL,
   fkCountry SMALLINT NOT NULL,
   PRIMARY KEY(pkLog)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LogBackuped(
   pkLogBackuped BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   path VARCHAR(255) NOT NULL,
   date VARCHAR(26),
   beginning VARCHAR(26) NOT NULL,
   end VARCHAR(26) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkScreenApproval BIGINT NOT NULL,
   fkCountry SMALLINT NOT NULL,
   fkUser BIGINT,
   PRIMARY KEY(pkLogBackuped)
   FOREIGN KEY (fkScreenApproval)
      REFERENCES ScreenApproval (pkScreenApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.CityAccount(
   pkCityAccount BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCity BIGINT NOT NULL,
   fkBankAccount BIGINT NOT NULL,
   fkTax BIGINT NOT NULL,
   PRIMARY KEY(pkCityAccount)
   FOREIGN KEY (fkCity)
      REFERENCES City (pkCity)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTax)
      REFERENCES Tax (pkTax)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Counter(
   pkCounter BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   dateApproved DATE,
   status INT NOT NULL DEFAULT 0,
   fkJuridicalPerson BIGINT NOT NULL,
   fkPerson BIGINT,
   PRIMARY KEY(pkCounter)
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxFormula(
   pkTaxFormula BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   number INT NOT NULL,
   rate REAL,
   companyType INT NOT NULL DEFAULT 1,
   status INT NOT NULL DEFAULT 0,
   fkTax BIGINT NOT NULL,
   fkTaxSettings BIGINT,
   fkTaxFormula BIGINT,
   fkBankAccount BIGINT,
   fkTaxSettingsCategory BIGINT,
   PRIMARY KEY(pkTaxFormula)
   FOREIGN KEY (fkTax)
      REFERENCES Tax (pkTax)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxSettings)
      REFERENCES TaxSettings (pkTaxSettings)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxFormula)
      REFERENCES TaxFormula (pkTaxFormula)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxSettingsCategory)
      REFERENCES TaxSettingsCategory (pkTaxSettingsCategory)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxSettingsCounter(
   pkTaxSettingsCounter BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   byPercent REAL,
   byOrderFixedPrice REAL,
   official BOOLEAN NOT NULL DEFAULT false,
   substituto BOOLEAN NOT NULL DEFAULT false,
   status INT NOT NULL DEFAULT 0,
   fkTaxSettings BIGINT NOT NULL,
   fkCounter BIGINT NOT NULL,
   PRIMARY KEY(pkTaxSettingsCounter)
   FOREIGN KEY (fkTaxSettings)
      REFERENCES TaxSettings (pkTaxSettings)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCounter)
      REFERENCES Counter (pkCounter)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LoanMoney(
   pkLoanMoney BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL,
   fkPerson BIGINT,
   fkJuridicalPerson BIGINT,
   fkLoanMoneyRequest BIGINT NOT NULL,
   fkPayment BIGINT,
   fkCurrency BIGINT,
   PRIMARY KEY(pkLoanMoney)
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLoanMoneyRequest)
      REFERENCES LoanMoneyRequest (pkLoanMoneyRequest)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkCurrency)
      REFERENCES Currency (pkCurrency)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LoanMoneyRequest(
   pkLoanMoneyRequest BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   value REAL NOT NULL,
   months INT NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkJuridicalPerson BIGINT,
   fkPerson BIGINT,
   fkLoanBankProgram BIGINT NOT NULL,
   PRIMARY KEY(pkLoanMoneyRequest)
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLoanBankProgram)
      REFERENCES LoanBankProgram (pkLoanBankProgram)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.PaymentTransfer(
   pkPaymentTransfer BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPayment BIGINT,
   fkBankAccount BIGINT,
   PRIMARY KEY(pkPaymentTransfer)
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LoanBankProgram(
   pkLoanBankProgram BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   description VARCHAR(32704) NOT NULL,
   beginning VARCHAR(26) NOT NULL,
   end VARCHAR(26) NOT NULL,
   interestRate REAL NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkBank BIGINT NOT NULL,
   fkLoanBankProgramProfile BIGINT,
   fkScreenApproval BIGINT,
   PRIMARY KEY(pkLoanBankProgram)
   FOREIGN KEY (fkBank)
      REFERENCES Bank (pkBank)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLoanBankProgramProfile)
      REFERENCES LoanBankProgramProfile (pkLoanBankProgramProfile)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkScreenApproval)
      REFERENCES ScreenApproval (pkScreenApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LoanBankProgramProfileCategory(
   pkLoanBankProgramProfileCategory BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT,
   fkCategory BIGINT NOT NULL,
   fkLoanBankProgramProfile BIGINT NOT NULL,
   PRIMARY KEY(pkLoanBankProgramProfileCategory)
   FOREIGN KEY (fkCategory)
      REFERENCES Category (pkCategory)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLoanBankProgramProfile)
      REFERENCES LoanBankProgramProfile (pkLoanBankProgramProfile)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.BalanceBlocked(
   pkBalanceBlocked BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   note VARCHAR(255) NOT NULL,
   value REAL NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkLoanMoney BIGINT NOT NULL,
   fkBalance BIGINT NOT NULL,
   PRIMARY KEY(pkBalanceBlocked)
   FOREIGN KEY (fkLoanMoney)
      REFERENCES LoanMoney (pkLoanMoney)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalance)
      REFERENCES Balance (pkBalance)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.BankBranch(
   pkBankBranch BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   branch VARCHAR(255) NOT NULL,
   fkBank BIGINT NOT NULL,
   fkJuridicalPerson BIGINT NOT NULL,
   PRIMARY KEY(pkBankBranch)
   FOREIGN KEY (fkBank)
      REFERENCES Bank (pkBank)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LoanBankProgramProfileBranch(
   pkLoanBankProgramProfileBranch BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkLoanBankProgramProfile BIGINT,
   fkBankBranch BIGINT,
   PRIMARY KEY(pkLoanBankProgramProfileBranch)
   FOREIGN KEY (fkLoanBankProgramProfile)
      REFERENCES LoanBankProgramProfile (pkLoanBankProgramProfile)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankBranch)
      REFERENCES BankBranch (pkBankBranch)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.PaymentBalance(
   pkPaymentBalance BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkPayment BIGINT NOT NULL,
   PRIMARY KEY(pkPaymentBalance)
   FOREIGN KEY (fkPayment)
      REFERENCES Payment (pkPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceOrderCanceled(
   pkServiceOrderCanceled BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date VARCHAR(26),
   detail VARCHAR(32704) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   pkServiceOrder BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkServiceOrderCanceled)
   FOREIGN KEY (pkServiceOrder)
      REFERENCES ServiceOrder (pkServiceOrder)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceOrderRefund(
   pkServiceOrderRefund BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   value REAL NOT NULL,
   fee REAL NOT NULL,
   date VARCHAR(26),
   status INT NOT NULL DEFAULT 0,
   fkServiceOrderPayment BIGINT NOT NULL,
   fkServiceOrderCanceled BIGINT NOT NULL,
   fkRefound BIGINT,
   fkRefoundFee BIGINT,
   PRIMARY KEY(pkServiceOrderRefund)
   FOREIGN KEY (fkServiceOrderPayment)
      REFERENCES ServiceOrderPayment (pkServiceOrderPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkServiceOrderCanceled)
      REFERENCES ServiceOrderCanceled (pkServiceOrderCanceled)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkRefound)
      REFERENCES Refound (pkRefound)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkRefoundFee)
      REFERENCES Refound (pkRefound)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.ServiceOrderAttachment(
   pkServiceOrderAttachment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkServiceOrder BIGINT NOT NULL,
   pkServiceContract BIGINT,
   fkUser BIGINT,
   fkAttachment BIGINT,
   PRIMARY KEY(pkServiceOrderAttachment)
   FOREIGN KEY (fkServiceOrder)
      REFERENCES ServiceOrder (pkServiceOrder)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (pkServiceContract)
      REFERENCES ServiceTemplateContract (pkServiceTemplateContract)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Refound(
   pkRefound BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkBalanceItem BIGINT NOT NULL,
   fkBalanceBlocked BIGINT,
   PRIMARY KEY(pkRefound)
   FOREIGN KEY (fkBalanceItem)
      REFERENCES BalanceItem (pkBalanceItem)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceBlocked)
      REFERENCES BalanceBlocked (pkBalanceBlocked)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.CategoryContractTemplate(
   pkCategoryContractTemplate BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   pkAttachment BIGINT,
   PRIMARY KEY(pkCategoryContractTemplate)
   FOREIGN KEY (pkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.FiscalModuleFunction(
   pkFiscalModuleFunction BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   code VARCHAR(255) NOT NULL,
   url VARCHAR(32704) NOT NULL,
   template VARCHAR(32704) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkFiscalModule BIGINT NOT NULL,
   PRIMARY KEY(pkFiscalModuleFunction)
   FOREIGN KEY (fkFiscalModule)
      REFERENCES FiscalModule (pkFiscalModule)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxReceiptFiscalModule(
   pkTaxReceiptFiscalModule BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   isSendingInGroup BOOLEAN NOT NULL DEFAULT false,
   dateSent VARCHAR(26),
   answeredRevenueItemCode VARCHAR(255),
   status INT NOT NULL DEFAULT 0,
   fkFiscalModuleFunction BIGINT NOT NULL,
   fkTaxReceipt BIGINT NOT NULL,
   PRIMARY KEY(pkTaxReceiptFiscalModule)
   FOREIGN KEY (fkFiscalModuleFunction)
      REFERENCES FiscalModuleFunction (pkFiscalModuleFunction)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxReceipt)
      REFERENCES TaxReceipt (pkTaxReceipt)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxReceiptCanceled(
   pkTaxReceiptCanceled BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date VARCHAR(26),
   status INT NOT NULL DEFAULT 0,
   fkTaxReceipt BIGINT NOT NULL,
   fkFiscalModuleFunction BIGINT NOT NULL,
   fkTaxReceiptFiscalModule BIGINT NOT NULL,
   PRIMARY KEY(pkTaxReceiptCanceled)
   FOREIGN KEY (fkTaxReceipt)
      REFERENCES TaxReceipt (pkTaxReceipt)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkFiscalModuleFunction)
      REFERENCES FiscalModuleFunction (pkFiscalModuleFunction)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxReceiptFiscalModule)
      REFERENCES TaxReceiptFiscalModule (pkTaxReceiptFiscalModule)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.IdentificationDocumentAttachment(
   pkIdentificationDocumentAttachment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkIdentificationDocument BIGINT,
   fkAttachment BIGINT,
   PRIMARY KEY(pkIdentificationDocumentAttachment)
   FOREIGN KEY (fkIdentificationDocument)
      REFERENCES IdentificationDocument (pkIdentificationDocument)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Tax(
   pkTax BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCountry SMALLINT,
   PRIMARY KEY(pkTax)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxReceiptCounterApproved(
   pkTaxReceiptCounterApproved BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date VARCHAR(26) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCounter BIGINT NOT NULL,
   fkAttachment BIGINT,
   PRIMARY KEY(pkTaxReceiptCounterApproved)
   FOREIGN KEY (fkCounter)
      REFERENCES Counter (pkCounter)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.DepartmentOfFinance(
   pkDepartmentOfFinance SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   region VARCHAR(255),
   status INT NOT NULL,
   fkJuridicalPerson BIGINT NOT NULL,
   fkResponsable BIGINT NOT NULL,
   fkAddress BIGINT NOT NULL,
   fkState SMALLINT NOT NULL,
   PRIMARY KEY(pkDepartmentOfFinance)
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkResponsable)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAddress)
      REFERENCES Address (pkAddress)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkState)
      REFERENCES State (pkState)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.FiscalModule(
   pkFiscalModule BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   code VARCHAR(255) NOT NULL,
   url VARCHAR(32704) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkTaxSettings BIGINT NOT NULL,
   PRIMARY KEY(pkFiscalModule)
   FOREIGN KEY (fkTaxSettings)
      REFERENCES TaxSettings (pkTaxSettings)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.FiscalModuleFunctionTag(
   pkFiscalModuleFunctionTag BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   sequence INT NOT NULL DEFAULT 1,
   tag VARCHAR(255),
   value VARCHAR(32704),
   length INT,
   completeWithZeroRight BOOLEAN NOT NULL DEFAULT false,
   completeWithZeroLeft BOOLEAN NOT NULL DEFAULT false,
   status INT NOT NULL DEFAULT 0,
   fkTagReference BIGINT NOT NULL,
   fkFiscalModuleFunctionTag BIGINT,
   PRIMARY KEY(pkFiscalModuleFunctionTag)
   FOREIGN KEY (fkTagReference)
      REFERENCES TagReference (pkTagReference)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkFiscalModuleFunctionTag)
      REFERENCES FiscalModuleFunctionTag (pkFiscalModuleFunctionTag)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TagReference(
   pkTagReference BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   code VARCHAR(255) NOT NULL,
   name VARCHAR(255) NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkCountry SMALLINT,
   PRIMARY KEY(pkTagReference)
   FOREIGN KEY (fkCountry)
      REFERENCES Country (pkCountry)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LoanBankProgramContract(
   pkLoanBankProgramContract BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkTemplateContract BIGINT NOT NULL,
   fkLoanBankProgram BIGINT,
   PRIMARY KEY(pkLoanBankProgramContract)
   FOREIGN KEY (fkTemplateContract)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLoanBankProgram)
      REFERENCES LoanBankProgram (pkLoanBankProgram)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LoanBankProgramApproval(
   pkLoanBankProgramApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkApproval BIGINT,
   fkLoanBankProgram BIGINT,
   PRIMARY KEY(pkLoanBankProgramApproval)
   FOREIGN KEY (fkApproval)
      REFERENCES Approval (pkApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLoanBankProgram)
      REFERENCES LoanBankProgram (pkLoanBankProgram)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.LogBackupedApproval(
   pkLogBackupedApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkLogBackuped BIGINT NOT NULL,
   fkApproval BIGINT NOT NULL,
   PRIMARY KEY(pkLogBackupedApproval)
   FOREIGN KEY (fkLogBackuped)
      REFERENCES LogBackuped (pkLogBackuped)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkApproval)
      REFERENCES Approval (pkApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.MainBankAccountApproval(
   pkMainBankAccountApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkMainBankAccount BIGINT NOT NULL,
   fkApproval BIGINT NOT NULL,
   PRIMARY KEY(pkMainBankAccountApproval)
   FOREIGN KEY (fkMainBankAccount)
      REFERENCES MainBankAccount (pkMainBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkApproval)
      REFERENCES Approval (pkApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxReceiptCounterPayment(
   pkTaxReceiptCounterPayment BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkTaxReceiptCounterApproved BIGINT NOT NULL,
   fkTransferMoney BIGINT,
   fkTaxReceiptCounterFee BIGINT,
   PRIMARY KEY(pkTaxReceiptCounterPayment)
   FOREIGN KEY (fkTaxReceiptCounterApproved)
      REFERENCES TaxReceiptCounterApproved (pkTaxReceiptCounterApproved)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTransferMoney)
      REFERENCES TransferMoney (pkTransferMoney)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkTaxReceiptCounterFee)
      REFERENCES TaxReceiptCounterFee (pkTaxReceiptCounterFee)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxReceiptCounterFee(
   pkTaxReceiptCounterFee BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   pkTaxReceiptCounterApproved BIGINT NOT NULL,
   pkTaxSettingsCounter BIGINT NOT NULL,
   fkBalanceItem BIGINT NOT NULL,
   PRIMARY KEY(pkTaxReceiptCounterFee)
   FOREIGN KEY (pkTaxReceiptCounterApproved)
      REFERENCES TaxReceiptCounterApproved (pkTaxReceiptCounterApproved)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (pkTaxSettingsCounter)
      REFERENCES TaxSettingsCounter (pkTaxSettingsCounter)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceItem)
      REFERENCES BalanceItem (pkBalanceItem)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.BalanceItem(
   pkBalanceItem BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   note VARCHAR(255) NOT NULL,
   date VARCHAR(26) NOT NULL,
   value REAL NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkBalance BIGINT,
   fkBalanceOrigin BIGINT,
   fkBalanceBlocked BIGINT,
   PRIMARY KEY(pkBalanceItem)
   FOREIGN KEY (fkBalance)
      REFERENCES Balance (pkBalance)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceOrigin)
      REFERENCES Balance (pkBalance)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceBlocked)
      REFERENCES BalanceBlocked (pkBalanceBlocked)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.WithdrawMoneyApproval(
   pkWithdrawMoneyApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkApproval BIGINT NOT NULL,
   fkWithdrawMoney BIGINT NOT NULL,
   PRIMARY KEY(pkWithdrawMoneyApproval)
   FOREIGN KEY (fkApproval)
      REFERENCES Approval (pkApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkWithdrawMoney)
      REFERENCES WithdrawMoney (pkWithdrawMoney)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.TaxSettingsApproval(
   pkTaxSettingsApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkTaxSettings BIGINT NOT NULL,
   fkApproval BIGINT NOT NULL,
   PRIMARY KEY(pkTaxSettingsApproval)
   FOREIGN KEY (fkTaxSettings)
      REFERENCES TaxSettings (pkTaxSettings)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkApproval)
      REFERENCES Approval (pkApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.FinancialModule(
   pkFinancialModule INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date VARCHAR(26) NOT NULL,
   wallet VARCHAR(255),
   status INT NOT NULL DEFAULT 0,
   fkMainBankAccount BIGINT NOT NULL,
   fkLogo BIGINT NOT NULL,
   fkScreenApproval BIGINT NOT NULL,
   fkUser BIGINT NOT NULL,
   PRIMARY KEY(pkFinancialModule)
   FOREIGN KEY (fkMainBankAccount)
      REFERENCES MainBankAccount (pkMainBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkLogo)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkScreenApproval)
      REFERENCES ScreenApproval (pkScreenApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkUser)
      REFERENCES User (pkUser)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.FinancialModuleFunction(
   pkFinancialModuleFunction BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   type INT NOT NULL,
   name VARCHAR(255) NOT NULL,
   information VARCHAR(32704),
   status INT NOT NULL DEFAULT 0,
   fkFinancialModule INT NOT NULL,
   PRIMARY KEY(pkFinancialModuleFunction)
   FOREIGN KEY (fkFinancialModule)
      REFERENCES FinancialModule (pkFinancialModule)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.FinanceModuleApproval(
   pkFinanceModuleApproval BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status INT NOT NULL DEFAULT 0,
   fkFinancialModule INT,
   fkApproval BIGINT,
   PRIMARY KEY(pkFinanceModuleApproval)
   FOREIGN KEY (fkFinancialModule)
      REFERENCES FinancialModule (pkFinancialModule)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkApproval)
      REFERENCES Approval (pkApproval)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.Bill(
   pkBill BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   code VARCHAR(255) NOT NULL,
   number VARCHAR(255) NOT NULL,
   controlCode VARCHAR(255),
   type SMALLINT NOT NULL DEFAULT 1,
   issueDate DATE NOT NULL,
   dueDate DATE NOT NULL,
   expirationDate DATE NOT NULL,
   value REAL NOT NULL,
   discount REAL,
   interest REAL,
   fee REAL,
   total REAL,
   status INT NOT NULL DEFAULT 0,
   fkPaymentBill BIGINT NOT NULL,
   fkBankAccount BIGINT NOT NULL,
   pkCurrency BIGINT NOT NULL,
   fkJuridicalPerson BIGINT,
   fkPerson BIGINT,
   fkAttachment BIGINT NOT NULL,
   fkBalanceItemFee BIGINT,
   PRIMARY KEY(pkBill)
   FOREIGN KEY (fkPaymentBill)
      REFERENCES PaymentBill (pkPaymentBill)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (pkCurrency)
      REFERENCES Currency (pkCurrency)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkJuridicalPerson)
      REFERENCES JuridicalPerson (pkJuridicalPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPerson)
      REFERENCES Person (pkPerson)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBalanceItemFee)
      REFERENCES BalanceItem (pkBalanceItem)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.BillFinancialModuleFunction(
   pkBillFinancialModuleFunction INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status SMALLINT NOT NULL DEFAULT 0,
   fkBill BIGINT NOT NULL,
   fkFinancialModuleFunction BIGINT NOT NULL,
   fkAttachment BIGINT,
   PRIMARY KEY(pkBillFinancialModuleFunction)
   FOREIGN KEY (fkBill)
      REFERENCES Bill (pkBill)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkFinancialModuleFunction)
      REFERENCES FinancialModuleFunction (pkFinancialModuleFunction)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.UserPaymentBankAccount(
   pkUserPaymentBankAccount BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   fkUserPayment BIGINT NOT NULL,
   fkBankAccount BIGINT NOT NULL,
   PRIMARY KEY(pkUserPaymentBankAccount)
   FOREIGN KEY (fkUserPayment)
      REFERENCES UserPayment (pkUserPayment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkBankAccount)
      REFERENCES BankAccount (pkBankAccount)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.CreditCardFinancialModuleFunction(
   pkCreditCardFinancialModuleFunction INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status SMALLINT NOT NULL DEFAULT 0,
   fkFinancialModuleFunction BIGINT,
   fkPaymentCredit BIGINT,
   PRIMARY KEY(pkCreditCardFinancialModuleFunction)
   FOREIGN KEY (fkFinancialModuleFunction)
      REFERENCES FinancialModuleFunction (pkFinancialModuleFunction)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkPaymentCredit)
      REFERENCES PaymentCredit (pkPaymentCredit)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

CREATE TABLE SVZ98608.FinancialModuleTermsOfService(
   pkFinancialModuleTermsOfService INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status SMALLINT NOT NULL DEFAULT 0,
   fkFinancialModule INT NOT NULL,
   fkAttachment BIGINT NOT NULL,
   PRIMARY KEY(pkFinancialModuleTermsOfService)
   FOREIGN KEY (fkFinancialModule)
      REFERENCES FinancialModule (pkFinancialModule)
      ON UPDATE RESTRICT ON DELETE CASCATE,
   FOREIGN KEY (fkAttachment)
      REFERENCES Attachment (pkAttachment)
      ON UPDATE RESTRICT ON DELETE CASCATE,
);

