

ALTER TABLE SVZ98608.Person DROP PRIMARY KEY;
ALTER TABLE SVZ98608.Person
ADD COLUMN newPrimaryKey SMALLINT NOT NULL
PRIMARY KEY (pkPerson, newPrimaryKey);
ALTER TABLE SVZ98608.Person ADD COLUMN newPrimary SMALLINT ;
ALTER TABLE SVZ98608.Person ALTER COLUMN newPrimary SET NOT NULL GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE SVZ98608.Person ADD PRIMARY KEY (pkPerson);

ALTER TABLE SVZ98608.Person DROP newPrimary;

------csdsdsd----------
SELECT TBNAME, IDENTITY, NAME, COLTYPE, LENGTH, NULLS, DEFAULT FROM 
SYSIBM.SYSCOLUMNS 
WHERE TBCREATOR = 'SVZ98608' and TBNAME = 'PERSON' ORDER BY TBNAME 

------csdsdsd----------

CREATE TABLE SVZ98608.NewTable(
   pkNewTable BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   type INT NOT NULL,
   PRIMARY KEY(pkNewTable)
);

------csdsdsd----------
ALTER TABLE SVZ98608.Person DROP COLUMN newPrimary;

      ALTER TABLE SVZ98608.Person 
      ADD COLUMN
         anothePrimary BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
         PRIMARY KEY(anothePrimary);
         

         ALTER TABLE SVZ98608.Person
          ALTER COLUMN  anothePrimary PRIMARY KEY(anothePrimary)

SELECT * FROM SVZ98608.Person

SELECT TABNAME, REFTABNAME, FK_COLNAMES, PK_COLNAMES FROM syscat.references WHERE TABSCHEMA = 'SVZ98608' AND TABNAME='PERSON'

SELECT * FROM SVZ98608.(SELECT
  *
FROM
  SYSIBM.SYSTABLES
WHERE
    type = 'T'
  AND
    creator = 'SVZ98608') group by 

SELECT CURRENT_DATE result FROM sysibm.sysdummy1;

SELECT systable.name as tableName, syscolumns.name as columnName, syscolumns.colType, syscolumns.length 
        FROM SYSIBM.SYSCOLUMNS as syscolumns, SYSIBM.SYSTABLES as systable
            WHERE systable.type = 'T'
            AND systable.creator = 'SVZ98608'
            AND syscolumns.tbname = systable.name
             
SELECT TBNAME, name, colType, length, NULLS, default FROM SYSIBM.SYSCOLUMNS WHERE TBCREATOR = 'SVZ98608' ORDER BY tbname