

ALTER TABLE SVZ98608.Person DROP PRIMARY KEY;
ALTER TABLE SVZ98608.Person
ADD COLUMN newPrimaryKey SMALLINT NOT NULL
PRIMARY KEY (pkPerson, newPrimaryKey);
ALTER TABLE SVZ98608.Person ADD COLUMN newPrimary SMALLINT ;
ALTER TABLE SVZ98608.Person ALTER COLUMN newPrimary SET NOT NULL GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE SVZ98608.Person ADD PRIMARY KEY (pkPerson);

ALTER TABLE SVZ98608.Person DROP newPrimary;

------csdsdsd----------
SELECT TBNAME, IDENTITY, NAME, COLTYPE, LENGTH, NULLS, DEFAULT FROM 
SYSIBM.SYSCOLUMNS 
WHERE TBCREATOR = 'SVZ98608' and TBNAME = 'PERSON' ORDER BY TBNAME 

------csdsdsd----------

CREATE TABLE SVZ98608.NewTable(
   pkNewTable BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   type INT NOT NULL,
   PRIMARY KEY(pkNewTable)
);

CREATE TABLE SVZ98608.NewTable2(
   pkNewTable BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   type INT NOT NULL,
   PRIMARY KEY(pkNewTable)
);

ALTER TABLE SVZ98608.NewTable ADD COLUMN fkNewTable2 BIGINT;

SELECT sysCol.TBNAME, sysCol.NAME, sysCol.IDENTITY, sysCol.COLTYPE, sysCol.LENGTH, sysCol.NULLS, sysCol.DEFAULT, sysCol.*
 FROM SYSIBM.SYSCOLUMNS as sysCol
 LEFT OUTER JOIN syscat.references as ref ON UPPER(ref.FK_COLNAMES)=UPPER(sysCol.NAME)
 WHERE sysCol.TBCREATOR = 'SVZ98608' 
 AND sysCol.TBNAME = 'NEWTABLE'

ALTER TABLE SVZ98608.NewTable
   FOREIGN KEY (fkNewTable2)
       REFERENCES NewTable2 (pkNewTable)
           ON UPDATE RESTRICT
           ON DELETE CASCADE;

SELECT CONSTNAME, TABNAME, REFTABNAME, FK_COLNAMES, PK_COLNAMES 
FROM SYSCAT.REFERENCES 
WHERE TABSCHEMA = 'SVZ98608' 
ORDER BY TABNAME

AND TABNAME = 'NEWTABLE'



ALTER TABLE SVZ98608.NewTable2 DROP COLUMN PKNEWTABLE

ALTER TABLE SVZ98608.NewTable DROP FOREIGN KEY FKSERVICE

------csdsdsd----------

SELECT sysCol.TBNAME, sysCol.NAME, sysCol.IDENTITY, sysCol.COLTYPE, sysCol.LENGTH, sysCol.NULLS, sysCol.DEFAULT, ref.CONSTNAME
 FROM SYSIBM.SYSCOLUMNS as sysCol 
 LEFT OUTER JOIN SYSCAT.REFERENCES as ref ON sysCol.NAME=ref.TABNAME
 WHERE sysCol.TBCREATOR = 'SVZ98608' 
 ORDER BY sysCol.TBNAME
 

 AND sysCol.TBCREATOR = 'SVZ98608' 
 AND ref.TABSCHEMA = 'SVZ98608' 

 AND sysCol.TBNAME = 'NEWTABLE'

SELECT * FROM SVZ98608.SERVICE WHERE status = 1

-----------------
SELECT TABNAME, REFTABNAME, FK_COLNAMES, PK_COLNAMES FROM syscat.references 
WHERE TABSCHEMA = 'SVZ98608' AND TABNAME = 'NEWTABLE'
--------------

      -- and reftabschema = 'ADMINISTRATOR' -- put your schema name here

      DELETE FROM table_name
[WHERE condition];


order by foreign_table,
         primary_table

ALTER TABLE SVZ98608.Person DROP COLUMN newPrimary;

      ALTER TABLE SVZ98608.Person 
      ADD COLUMN
         anothePrimary BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
         PRIMARY KEY(anothePrimary);
         

         ALTER TABLE SVZ98608.Person
          ALTER COLUMN  anothePrimary PRIMARY KEY(anothePrimary)

SELECT * FROM SVZ98608.Person

SELECT TABNAME, REFTABNAME, FK_COLNAMES, PK_COLNAMES FROM syscat.references WHERE TABSCHEMA = 'SVZ98608' AND TABNAME='PERSON'

SELECT * FROM SVZ98608.(SELECT
  *
FROM
  SYSIBM.SYSTABLES
WHERE
    type = 'T'
  AND
    creator = 'SVZ98608') group by 

SELECT CURRENT_DATE result FROM sysibm.sysdummy1;

SELECT systable.name as tableName, syscolumns.name as columnName, syscolumns.colType, syscolumns.length 
        FROM SYSIBM.SYSCOLUMNS as syscolumns, SYSIBM.SYSTABLES as systable
            WHERE systable.type = 'T'
            AND systable.creator = 'SVZ98608'
            AND syscolumns.tbname = systable.name
             
SELECT TBNAME, name, colType, length, NULLS, default FROM SYSIBM.SYSCOLUMNS WHERE TBCREATOR = 'SVZ98608' ORDER BY tbname

--------------------STATES--------------------
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('11', 'Rondônia', 'RO');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('12', 'Acre', 'AC');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('13', 'Amazonas', 'AM');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('14', 'Roraima', 'RR');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('15', 'Pará', 'PA');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('16', 'Amapá', 'AP');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('17', 'Tocantins', 'TO');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('21', 'Maranhão', 'MA');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('22', 'Piauí', 'PI');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('23', 'Ceará', 'CE');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('24', 'Rio Grande do Norte', 'RN');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('25', 'Paraíba', 'PB');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('26', 'Pernambuco', 'PE');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('27', 'Alagoas', 'AL');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('28', 'Sergipe', 'SE');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('29', 'Bahia', 'BA');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('31', 'Minas Gerais', 'MG');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('32', 'Espírito Santo', 'ES');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('33', 'Rio de Janeiro', 'RJ');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('35', 'São Paulo', 'SP');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('41', 'Paraná', 'PR');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('42', 'Santa Catarina', 'SC');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('43', 'Rio Grande do Sul', 'RS');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('50', 'Mato Grosso do Sul', 'MS');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('51', 'Mato Grosso', 'MT');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('52', 'Goiás', 'GO');
INSERT INTO SVZ98608.State (code, name, abbreviation) VALUES ('53', 'Distrito Federal', 'DF');
--------------------STATES--------------------

